<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdminDashboard.aspx.cs" Inherits="AdminDashboard" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>
                <asp:Label ID="Label1" runat="server" Text="Administrator Dashboard"></asp:Label>
            </h1>
            <hr />
            <h2>
                <asp:Label ID="Label2" runat="server" Text="Users"></asp:Label>
            </h2>
            <asp:Label ID="Label4" runat="server" Text="Total Users:" Style="font-size: large"></asp:Label>
            <asp:Label ID="Lbl_totalUsers" runat="server" Text="0" Style="font-size: large"></asp:Label>
            <br />
            <asp:Label ID="Label5" runat="server" Text="Active Users:" Style="font-size: large"></asp:Label>
            <asp:Label ID="Lbl_activeUsers" runat="server" Text="0" Style="font-size: large"></asp:Label>
            <br />
            <br />
            <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" ReadOnly="True" SortExpression="Id" InsertVisible="False" />
                    <asp:BoundField DataField="UserName" HeaderText="UserName" SortExpression="UserName" />
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                    <asp:CheckBoxField DataField="IsActive" HeaderText="IsActive" SortExpression="IsActive" />
                    <asp:CheckBoxField DataField="IsDisable" HeaderText="IsDisable" SortExpression="IsDisable" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:AfekaMiniTorrentDBConnectionString %>" DeleteCommand="DELETE FROM [User] WHERE [Id] = @original_Id" InsertCommand="INSERT INTO [User] ([UserName], [Password], [IsActive], [IsDisable]) VALUES (@UserName, @Password, @IsActive, @IsDisable)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [User]" UpdateCommand="UPDATE [User] SET [UserName] = @UserName, [Password] = @Password, [IsActive] = @IsActive, [IsDisable] = @IsDisable WHERE [Id] = @original_Id">
                <DeleteParameters>
                    <asp:Parameter Name="original_Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="UserName" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="IsActive" Type="Boolean" />
                    <asp:Parameter Name="IsDisable" Type="Boolean" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="UserName" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="IsActive" Type="Boolean" />
                    <asp:Parameter Name="IsDisable" Type="Boolean" />
                    <asp:Parameter Name="original_Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <h3>
                <asp:Label ID="Label7" runat="server" Text="Add a new user"></asp:Label>
            </h3>
            <asp:Label ID="Label8" runat="server" Text="UserName:"></asp:Label>
            &nbsp;&nbsp;
            <asp:TextBox ID="UserName" runat="server"></asp:TextBox>
            &nbsp;&nbsp;
            <asp:Label ID="Label9" runat="server" Text="Password:"></asp:Label>
            &nbsp;&nbsp;
            <asp:TextBox ID="Password" runat="server"></asp:TextBox>
            &nbsp;&nbsp;
            <asp:Button ID="Btn_addNewUser" runat="server" Text="Add" OnClick="Btn_addNewUser_Click" />
            <br />
            <asp:Label ID="Lbl_userNameExist" runat="server" Text="*UserName already exist!" ForeColor="Red" Visible="False"></asp:Label>
            <br />
            <asp:Label ID="Lbl_emptyFields" runat="server" Text="*There are empty fields!" ForeColor="Red" Visible="False"></asp:Label>
            <br />
            <hr />
            <h2>
                <asp:Label ID="Label3" runat="server" Text="Files"></asp:Label>
            </h2>
            <asp:Label ID="Label6" runat="server" Text="Total files:" Style="font-size: large"></asp:Label>
            <asp:Label ID="Lbl_totalFiles" runat="server" Text="0" Style="font-size: large"></asp:Label>
            <br />
            <br />
            <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="Id" DataSourceID="SqlDataSource2" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="FileName" HeaderText="FileName" SortExpression="FileName" />
                    <asp:BoundField DataField="FileSize" HeaderText="FileSize" SortExpression="FileSize" />
                    <asp:BoundField DataField="NumOfPeers" HeaderText="NumOfPeers" SortExpression="NumOfPeers" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:AfekaMiniTorrentDBConnectionString %>" DeleteCommand="DELETE FROM [File] WHERE [Id] = @Id" InsertCommand="INSERT INTO [File] ([FileName], [FileSize], [NumOfPeers]) VALUES (@FileName, @FileSize, @NumOfPeers)" SelectCommand="SELECT * FROM [File]" UpdateCommand="UPDATE [File] SET [FileName] = @FileName, [FileSize] = @FileSize, [NumOfPeers] = @NumOfPeers WHERE [Id] = @Id">
                <DeleteParameters>
                    <asp:Parameter Name="Id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="FileName" Type="String" />
                    <asp:Parameter Name="FileSize" Type="Int64" />
                    <asp:Parameter Name="NumOfPeers" Type="Int32" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="FileName" Type="String" />
                    <asp:Parameter Name="FileSize" Type="Int64" />
                    <asp:Parameter Name="NumOfPeers" Type="Int32" />
                    <asp:Parameter Name="Id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <asp:Panel ID="Panel1" runat="server" DefaultButton="Btn_search">
                <br />
                <asp:Label ID="Label10" runat="server" Text="File Name:"></asp:Label>
                &nbsp;&nbsp;
            <asp:TextBox ID="FileName" runat="server"></asp:TextBox>
                &nbsp;&nbsp;
            <asp:Button ID="Btn_search" runat="server" Text="Search" OnClick="Btn_search_Click" />
                &nbsp;&nbsp;
            <asp:Label ID="Lbl_emptyFileName" runat="server" Text="*File name is empty!" ForeColor="Red" Visible="False"></asp:Label>
            </asp:Panel>
            <br />
            <asp:GridView ID="GridView3" runat="server" AllowPaging="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="Id" DataSourceID="ObjectDataSource1" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                    <asp:BoundField DataField="FileName" HeaderText="FileName" SortExpression="FileName" />
                    <asp:BoundField DataField="FileSize" HeaderText="FileSize" SortExpression="FileSize" />
                    <asp:BoundField DataField="NumOfPeers" HeaderText="NumOfPeers" SortExpression="NumOfPeers" />
                </Columns>
                <EditRowStyle BackColor="#2461BF" />
                <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#EFF3FB" />
                <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#F5F7FB" />
                <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                <SortedDescendingCellStyle BackColor="#E9EBEF" />
                <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" SelectMethod="SearchFileName" TypeName="DAL.OperationsDB">
                <SelectParameters>
                    <asp:ControlParameter ControlID="FileName" DefaultValue="" Name="fileName" PropertyName="Text" Type="String" />
                </SelectParameters>
            </asp:ObjectDataSource>
            <br />
            <br />
            <br />
            <br />
            <br />
            <br />
        </div>
    </form>
</body>
</html>
